### ISSUE TITLE
Hydrogen Hack

### ISSUE THREAD

**Issue by theGreatWhiteShark** [Houston4444/RaySession#114]
at tag: v0.10.1

---

Hey @Houston4444 

First of all, let me give you some props: RaySession improved quite a bit since the last time I checked. Very good work!

I noticed that `Hydrogen` is getting started  using a Ray-Hack. The latest release (v1.1.0-beta) has already full NSM support. It is triggered as soon as the `NSM_URL` environmental variable is set.  But this does not seem to happen in `RaySession`. Are you setting the aforementioned variable?

**Comment by Houston4444** [comment]
Hi !

> First of all, let me give you some props: RaySession improved quite a bit since the last time I checked. Very good work!

Thanks a lot ! The best is coming soon : see #112

> I noticed that Hydrogen is getting started using a Ray-Hack. The latest release (v1.1.0-beta) has already full NSM support.

The Hydrogen template in RaySession still uses Ray-Hack, because RaySession can't know which version of Hydrogen is installed. The previous Hydrogen version NSM support was so problematic that Ray-Hack is still more reliable.

If you start Hydrogen with "Executable" window (and not "Application"), you will see that Hydrogen uses the NSM protocol correctly.

> It is triggered as soon as the NSM_URL environmental variable is set. But this does not seem to happen in RaySession. Are you setting the aforementioned variable?

Ray-Hack pseudo-protocol doesn't set NSM_URL. This allows to test or run NSM compatible program without NSM support and specific arguments.

Important Note:
You can add a template to RaySession to say to RaySession that 'Hydrogen' uses NSM.
The only thing you have to do is to make your program install a simple xml file at path `/etc/xdg/raysession/client_templates/30_hydrogen/client_templates.xml` . (30_hydrogen can vary, but it must start with a 2 digits number lower than 40).

This file should have this contents :

```
<RAY-CLIENT-TEMPLATES>
    <Client-Template template-name="Hydrogen" client_id="hydrogen" executable="hydrogen"/>
</RAY-CLIENT-TEMPLATES>
```

I 'am still here if any questions.
Cheers.

**Comment by theGreatWhiteShark** [comment]
I agree. The NSM support in previous versions didn't worked at all.

Do you have a permanent URL to some part of doc/manual/wiki that covers this specific topic? Otherwise I would link this issue in the Hydrogen documentation since I recommend RaySession in there.

**Comment by Houston4444** [comment]
Dev and packagers documentation is still to be written, sorry.
Not sure to have been understood correctly, the note I wrote in previous message is for developers or packagers, not for users.
Do you think that Hydrogen could install a such file when user installs it to its system with `make install` or something else (I don't know what Hydrogen uses) ?

**Comment by theGreatWhiteShark** [comment]
> Dev and packagers documentation is still to be written, sorry.
 
Don't worry.

> Not sure to have been understood correctly, the note I wrote in previous message is for developers or packagers, not for users.
Do you think that Hydrogen could install a such file when user installs it to its system with make install or something else (I don't know what Hydrogen uses) ?

I see. TBH I don't feel comfortable putting a file in a systems folder that is neither associated the program being installed nor a preexisting system folder. But I would create a dedicated page in the Hydrogen wiki (can be edited by everyone + more dynamic) and link it in the docs.

> RaySession can't know which version of Hydrogen is installed.

This could be also dealt with the `--version` flag on the command line. Or I could provide you with a string that is only available in versions with proper NSM support. But I of course understand if you don't want to integrate exceptions for every other program :wink:

**Comment by Houston4444** [comment]
> TBH I don't feel comfortable putting a file in a systems folder that is neither associated the program being installed nor a preexisting system folder.

I perfectly understand, this thing has been done for packagers more than for devs.

 > But I would create a dedicated page in the Hydrogen wiki (can be edited by everyone + more dynamic) and link it in the docs.

As I just said, this can helps packagers. For users, there is a very simple solution : In RaySession menu, select Add -> Executable, type hydrogen, launch. Then Click on Hydrogen icon and "Save as application template", that is done, your Hydrogen Application template is ready in "Add Application" dialog.

> This could be also dealt with the --version flag on the command line.

I know this. The problem is that RaySession searches for applications each time "Add Application" dialog is open. If we have only hydrogen it's not a big deal, but if there are many ones to check version this way, this will slow down the process significantly. And some applications loads a lot of things even if we just ask them their version.

However, this method already exists in RaySession (older than check for '/nsm/server/announce' in executable), so, no work  is needed to achieve this. Just ensure me that if I check the two first digits, version >= 1.1, is it ok ?

> Or I could provide you with a string that is only available in versions with proper NSM support.

No thanks ;) This is dirty on both sides. One other solution could be to define a key in .desktop file, if possible the same for all NSM session managers, I have to discuss that with theses other devs.

**Comment by theGreatWhiteShark** [comment]
> I know this. The problem is that RaySession searches for applications each time "Add Application" dialog is open. If we have only hydrogen it's not a big deal, but if there are many ones to check version this way, this will slow down the process significantly. And some applications loads a lot of things even if we just ask them their version.

I see. Just checked, Hydrogen does already do a good job in this and doesn't load anything when printing the version.

> However, this method already exists in RaySession (older than check for '/nsm/server/announce' in executable), so, no work is needed to achieve this. Just ensure me that if I check the two first digits, version >= 1.1, is it ok ?

I can guarantee this. However, I just realized that the code didn't handle this right up to now and just displays "hydrogen" with no version at all. This is fixed now and will work in 1.1 where it displays something like "hydrogen 1.1.0-'4ca09c0e'" (with the commit hash only when installing from a git commit without tag).

**Comment by Houston4444** [comment]
Thanks a lot for this checks and this fix. I'll test this new hydrogen version and modify the template if all is ok ( I don't doubt)!

**Comment by Houston4444** [comment]
The new release should fix this issue and launch Hydrogen with NSM if hydrogen > 1.1.0.
I did not verify. If it is not the case, I am pretty sure that a bugfix release will come soon.

**Comment by theGreatWhiteShark** [comment]
Nice! Works like a charm. 

Just to be sure: is it if `hydrogen > 1.1.0` or `hydrogen >= 1.1.0`? (as the 1.1.0 release will be the first official and stable one with full NSM support)

**Comment by Houston4444** [comment]
thanks.
Normally it is `hydrogen >= 1.1.0`. Hopefully it is not hydrogen specific and we can reproduce the behavior with other programs without code modification (only modifying .xml file in client_templates).
