### ISSUE TITLE
Compatibility with Bespoke

### ISSUE THREAD

**Issue by tobiasBora** [Houston4444/RaySession#130]
Bespoke is a great program, but RaySession won't save the project at the end (so we need to manually save it). Would it be possible to make Bespoke compatible with RaySession?

Related: https://github.com/BespokeSynth/BespokeSynth/issues/503

**Comment by Houston4444** [comment]
See this with bespoke devs! To work with RS it must have NSM support.

**Comment by tobiasBora** [comment]
Ok! I was just curious because sooper looper was not working with NSM but does vork in RaySessi ou n, so I was thinking that you may have some tricks to support non NSM compatible programs. Anyway, I'll the is se ue then, thanks.

**Comment by Houston4444** [comment]
Sooperlooper in RaySession is a workaround I made. It was possible because Sooperlooper is a daemon controlled by a GUI with OSC. 
You can still use bespoke with Ray-Hack, it won't save your bespoke instance, but it can be more comfortable, especially if your window manager uses X11 (and not Wayland).
