### ISSUE TITLE
"Refresh applications" does not detect Ardour 7

### ISSUE THREAD

**Issue by lootre** [Houston4444/RaySession#153]
Hi ! I've uninstalled Ardour 6.9 and installed Ardour 7.2 instead. When running RaySession and opening the "Add application" dialog box, Ardour disappeared from the application list and the button "Refresh applications" does not detect the new installation of Ardour.

Is there a was to manually update this list ?

Running version 0.13.0

**Comment by Houston4444** [comment]
Ardour7 template has been added to the master branch some weeks ago, so this will be in the next release (soon).

Waiting for this you can run "Ardour7" (or maybe "ardour7", depending on the ardour provenance)  with the "add executable" button, set the prefix name combo box to "Session Name" if you want the ardour session to be named as the ray session.

Then, save the client as template if you want to have Ardour7 in the "Add application" dialog.

I close the issue because Ardour7 template is already present in master branch.

**Comment by lootre** [comment]
Thank you very much for the answer and for the good job ! RaySession is awesome.
