### ISSUE TITLE
Feature request: start in tray

### ISSUE THREAD

**Issue by mahlonsmith** [Houston4444/RaySession#202]
Hopefully a small request!   I like to always have raysession running, I find it to be a superior interface for system routing, etc.   I'd like it to start up to the tray on login without displaying itself -- perhaps a "-m / --minimized" flag?

**Comment by Houston4444** [comment]
I am not opposed, although it needs to check that systray mode is on "always".

Personally, I'll suggest you to think the thing in another way. I made the window available in systray because it was often asked, but in reality, I think it is not needed at all.
In fact, the RaySession GUI is just a remote for its daemon. If you open a session at computer startup with the following command:

`ray_control open_session "My Session"`

it starts the daemon, open the session and everything should works. If then you launch RaySession because you need the GUI, it will autoconnect to this running daemon and you will see your session. The advantage is that when you don't need it, GUI is not running at all.

**Comment by mahlonsmith** [comment]
👍 Yeah, this is perfecto.  Thanks!
