### ISSUE TITLE
unknown osc message: /ray/session/add_proxy 

### ISSUE THREAD

**Issue by newlaurent62** [Houston4444/RaySession#56]
Hello,

I'm trying to create a ray-proxy client using:

`ray_control add_proxy`

but it returns the following error on the master branch:
```
unknown osc message: /ray/session/add_proxy 
```
BR,
Laurent

**Comment by newlaurent62** [comment]
ok i found the error:

ray_control add_proxy EXECUTABLE

The --help-all does not mention EXECUTABLE parameter for add_proxy

at least in french.

**Comment by newlaurent62** [comment]
When i execute the following :

clientID=$(ray_control add_proxy alt-config-session)
ray_control client $clientID set_proxy_properties arguments:"-- Jamulus"
Ray Proxy (a_csession_3) seems to not be a proxy client !

And indeed I would expect this command to create a folder named "$raysession_name.$clientID"  and in that dir put a ray-proxy.xml file that contains the properties set with ray_control set_proxy_properties but this not true.

How can i do that apart from creating the ray-proxy.xml manually or relying on XML format ?

**Comment by Houston4444** [comment]
Thanks for the issue report.
I'll try to fix it soon.
Je ne savais pas que tu parlais français, c'est très bien de parler anglais ici pour que tous ceux qui y passent comprennent de quoi il retourne, par contre, quand c'est assez complexe tu peux écrire aussi en français ça me facilite la tâche !

**Comment by Houston4444** [comment]
Ok I found why.
At set_proxy_properties, daemon checks if it is a proxy by checking the ray-proxy file.
Seeing this, set_proxy_properties  is a problematic thing, because if client is running, theses changes could not be affect.
I have to review theses messages (add_executable, add_proxy, set_proxy_properties...).

**Comment by newlaurent62** [comment]
Je t'avoue que mon anglais n'est pas toujours optimal ... J'utilise bcp google traduction ! 

Ok so while this feature is missing, i will try to generate the ray-proxy.xml file with a script.

**Comment by newlaurent62** [comment]
I have code that creates a session for NSM and RAY using XML or ray_control.

for NSM : My session is created, loaded and runs using nsm proxies.

for RAY_XML : My session is created, loaded but programs wont run (NSM_CLIENT_ID seems to not be defined by the client id attribute from raysession.xml (Its value is always "Ray Proxy"). To create raysession.xml without ray_control, i used the same clientID generation algorithm as NSM. Are there some restrictions on the clientID in ray ?

RAY_CONTROL : My session cannot be created using ray_control because to create a clientID, i need to create a proxy file which is placed in a directory that depends on the ID ... We've already discuss it. I will wait for your review of these ray_control messages. (add_executable, add_proxy, set_proxy_properties ...)

I have still to define the nsm/ray saving levels/signals of my set of applications. And i will have a workable wizard example.

**Comment by Houston4444** [comment]
I remade the API of ray_control about add_executable.
There is no more add_proxy method. Instead use `ray_control add_executable EXECUTABLE via_proxy`.
You can also use `not_start` as option to add_executable to not start the added client. 
See `ray_control --help-clients` if you want.
ray_control set_proxy_properties won't works if client is started (because changes could be erase by proxy).

A good way to do could be something like this:
client_id=$(ray_control add_executable EXECUTABLE via_proxy not_start)
ray_control set_proxy_properties "executable:EXECUTABLE
arguments:some arguments
save_signal:0
no_save_level:1"

**Comment by Houston4444** [comment]
> (NSM_CLIENT_ID seems to not be defined by the client id attribute from raysession.xml (Its value is always "Ray Proxy")

This bug has just been fixed

**Comment by newlaurent62** [comment]
Ok thanks a lot ! 

I tested successfully:

- NSM_CLIENT_ID : OK
- ray_control add_executable $executable via_proxy not_start : OK
- ray_control client $clientID set_description : OK

Now all the wizard generation modes are working and load the session correclty.

**Comment by newlaurent62** [comment]
ray_control client $clientID set_proxy_properties OK
