### ISSUE TITLE
How to deal with automatic "unwanted" connections

### ISSUE THREAD

**Issue by BrunoVernay** [Houston4444/RaySession#66]
It would be nice to have a way to disconnect mainly the audio connection made by some applications at startup (Ardour and MuseScore typically will create connections or maybe it is Jack, because MuseScore is explicitly configured to NOT "Remember connection")

It would be nice to have a "Cleanup" done maybe 1 second after launching the application.
Currently I have to remove these connections manually with QJackCtl ...

Maybe an easier solution (for me) would be to be able to call a shell script once the application are ready (I think Ardour at least send this info). I used to have scripts to manage "sessions", so I already have the script to disconnect my unwanted connections.

**Comment by newlaurent62** [comment]
sometimes there is a **command line option** or a **configuration option** in **config file** to explicitely not autoconnect. It's a commonly found option in program using jack.

**Comment by BrunoVernay** [comment]
As I said I already tried to configure the client app. as much as possible.
And clearly what I ask for is a workaround, the problem originate from these apps.

But as I was rebasing my fork, it looks like there will be more scriptability to raySession, hopefully I maybe able to script an easy workaround.

**Comment by Houston4444** [comment]
Yes, use session scripts !
copy the folder `session_scripts/base scripts/ray-scripts`  to your session path or to your root session dir (~/Ray Sessions , by default).
If you copy this dir to your root dir, scripts will apply to all your sessions.

In the load.sh, write your disconnection script after `ray_control run_step`. Because MuseScore is not NSM compatible, it may be ready for RS a long time before it is really ready, so just write a loop waiting for its jack ports (checking this with jack_lsp).

**Comment by BrunoVernay** [comment]
It works. Thank you. It makes it easy to adapt to different situations.
