### ISSUE TITLE
RAY_CONTROL_PORT not set for proxy client

### ISSUE THREAD

**Issue by newlaurent62** [Houston4444/RaySession#69]
Hello,

When i open two raysession application instances with two different session, my client script does not get the right ray-daemon port to get the ray session path on the second opened session.

The RAY_CONTROL_PORT env variable seems to not be set for proxy client.

BR,
Laurent

**Comment by newlaurent62** [comment]
I just added after line 93 src/daemon/client.py
https://github.com/Houston4444/RaySession/blob/master/src/daemon/client.py#L93

`        process_env.insert('RAY_CONTROL_PORT', str(self.getServerPort()))`

And starting two raysession application instances with two different sessions works now with my wrapper script. This may be of use if we want to connect two use case. But i have not yet an example ...

**Comment by Houston4444** [comment]
This is not the good way to do, As I said, I don't want to add env var to NSM clients because I don't wan't that devs develop programs compatible with RaySession and not with other NSM managers.
That said, ray-proxy could set the RAY_CONTROL_PORT because it knows it, it is at the end of $NSM_URL .

But, 
I am going to make an important change to RaySession, and I think I will be considered as heretic for some inquisitors: Manage directly NSM incompatible clients with a new protocol (which behaves exactly as ray-proxy). This protocol is called Ray-Hack (because you speak french, you know what a "réac" is). You can test it in branch so_boring_proxy, add executable from GUI and uncheck NSM protocol checkbox. This is really near near ready.

More,
You can also use client scripts.
This is totally undocumented for the moment.
client scripts are in folder `ray-script.$CLIENT_ID` in the session folder.
They can be named `start.sh` , `save.sh` and `stop.sh`.
Example for start.sh :

```
#!/bin/bash

# script here
ray_control client $RAY_CLIENT_ID start
# script here
```

**Comment by newlaurent62** [comment]
That sounds very interesting !

Will it be possible to get the client pid ? (not the load.sh script pid)

I will give it a try when i will finish my current task of rework the wizard.

**Comment by Houston4444** [comment]
Yes, that could be possible, but obviously not for start.sh, because the process is not started ;)
I will put a get_pid for client for ray_control, but I can also set RAY_CLIENT_PID (faster for script).

**Comment by newlaurent62** [comment]
ok for RAY_CLIENT_PID variable if initialized to special value if client start failed.

**Comment by newlaurent62** [comment]
It's seems that NSM_URL variable is not set in the ray-proxy environment.

**Comment by Houston4444** [comment]
> It's seems that NSM_URL variable is not set in the ray-proxy environment. It is empty.

This is normal. I need to modify ray-proxy code to implement RAY_CONTROL_PORT.

**Comment by Houston4444** [comment]
> ok for RAY_CLIENT_PID variable if initialized to special value if client start failed.

humm,
for start.sh, no pid because program is not launched at script start (empty var seems ok to me),
for save.sh and close.sh, theses scripts can be launch only if program is running, so the pid is necessarily correct.

**Comment by newlaurent62** [comment]
There's something i'm missing ... Will i be able to do something like this ?
```

#!/bin/bash

# script here

pid=$(ray_control client $RAY_CLIENT_ID start)

if [ $pid -gt 0 ]; then
  we do stuff with the pid of $RAY_CLIENT_ID
else
  we do stuff and exit with error status
fi
```

**Comment by Houston4444** [comment]
No.
More something like that:

```
#!/bin/bash

# script here

if ray_control client $RAY_CLIENT_ID start;then
 pid=$(ray_control client $RAY_CLIENT_ID get_pid)
 we do stuff with the pid of $RAY_CLIENT_ID
else
 we do stuff and exit with error status
fi
```

when the get_pid method will be implemented.

**Comment by Houston4444** [comment]
Ok, now get_pid is implemented on master branch. That was not long ;)

**Comment by Houston4444** [comment]
and ray-proxy sets RAY_CONTROL_PORT

**Comment by newlaurent62** [comment]
It seems that the returned pid is the ray-proxy pid and not the real client.

Can it be changed to the real client pid or can you provide another get_child_pid command or something ?

**Comment by Houston4444** [comment]
It is something quite long to do
This is one more reason to not work on proxy anymore and focus on Ray-Hack client

**Comment by newlaurent62** [comment]
Ok. Now i use ray-proxy without  wrapper.

Catia uses `ray_control client get_pid` and do `pgrep -P pid` to get the ray-proxy child process pid. Catia handles several raysessions but does not yet implement layers. By clicking on jack clients, you can go to the corresponding app or to the raysession application if the client is not started. If the jack  client is not bind to raysession then you can also set a default application. 

I have other ideas that would require ray-hack to implement i think.

I would like to explore sending keyboard shortcut to softwares that do not implement nsm protocol neither handle system signal for save operation.

I do an extensive use of X11 tools to achieve these functionalities. Currently i use wmctrl

**Comment by Houston4444** [comment]
It would be nice to have a repository to look to test this !

> I would like to explore sending keyboard shortcut to softwares that do not implement nsm protocol neither handle system signal for save operation.
> 
> I do an extensive use of X11 tools to achieve these functionalities. Currently i use wmctrl

Take a look to `session_scripts/save_via_window` it achieves this at session save with xdotools.
send Ctrl+S to windows is something I saw a long time ago, I won't add this feature natively in RS because it will never works with Wayland, and I don't want to propose very nice features that will be disabled in the future (if future is Wayland).
