### ISSUE TITLE
[Question] Command or script to load a session/ a sub-session ?

### ISSUE THREAD

**Issue by moonshaadow** [Houston4444/RaySession#83]
Hello there. This is an idea from my former usage of ladish.
I know RS is very different, bur it could help to explain what I'm trying to do :
In ladish there is the concept of 'rooms'. This is in a certain way similar to the concept of child session in RS.
In ladish, I can have different rooms, and load at any time a session in a room, in order to change instruments, FX or whatever,  simply by a command, while keep other rooms running.
Is there currently a simple way to do something like that ?
I noticed there is no ability to load a session in a child session, so I suppose it is not possible in this way.

Or someone does have any idea for performing something similar ?

**Comment by Houston4444** [comment]
TBH, sub-sessions are here by accident, It was a programmatic step to go to network sessions. I don't really see the interest to use them. That said, I don't see why you can not do that with them.

In ladish, rooms are really interesting because a studio is jack dependent, rooms can be a way to change project without stop/restart jack, in RaySession (or NSM) we don't need that.

RaySession can run many instances, there is no problem with that, so you can run your main session, and another raysession instance where you can change the second session (I think it's better to change root directory starting raysession this way `raysession --session-root "Other Ray Sessions"`).
 
Perhaps, for JACK connections memory and a practical organization, the best could be (if possible in your case), to add a Carla-PatchBay, then add your jack applications from this Carla-Patchbay instance. This way you will have a carla-patchbay jack group in main patch (2 audio in/out, 1 midi in/out) and your sub-applications in carla-patchbay patchbay.

**Comment by moonshaadow** [comment]
Thank's for the long response. Yes, now it seems trivial to use many instances, I don't know where was my mind ;-) 
That said, it's easy to start a instance with a session by command line, but is there a command line way to open a session in an existing RS instance? My main idea is to have something usable with no mouse actions, or just a few, for live things.

**Comment by Houston4444** [comment]
> is there a command line way to open a session in an existing RS instance?

`ray_control open_session my_session` if my_session is in sessions root folder (`~/Ray Sessions` by default), or `ray_control open_session path/to/my_session` if my_session is in a sub-folder.
Type `ray_control --help-all` to see all possible actions doable via command line.

**Comment by moonshaadow** [comment]
Nice! Thank you.
